[[male]]
"им" = "Марк"
"ро" = "Марка"
"да" = "Марку"
"ви" = "Марка"
"тв" = "Марком"
"пр" = "Марке"

[[male]]
"им" = "Джон"
"ро" = "Джона"
"да" = "Джону"
"ви" = "Джона"
"тв" = "Джоном"
"пр" = "Джоне"

[[male]]
"им" = "Бен"
"ро" = "Бена"
"да" = "Бену"
"ви" = "Бена"
"тв" = "Беном"
"пр" = "Бене"


[[female]]
"им" = "Алиса"
"ро" = "Алисы"
"да" = "Алисе"
"ви" = "Алису"
"тв" = "Алисой"
"пр" = "Алисе"

[[female]]
"им" = "Матильда"
"ро" = "Матильды"
"да" = "Матильде"
"ви" = "Матильду"
"тв" = "Матильдой"
"пр" = "Матильде"

[[female]]
"им" = "Ава"
"ро" = "Авы"
"да" = "Аве"
"ви" = "Аву"
"тв" = "Авой"
"пр" = "Аве"