
#- Baker
#- Child
#- Cooper

[[male]]
"им" = "Бейкер"
"ро" = "Бейкера"
"да" = "Бейкеру"
"ви" = "Бейкера"
"тв" = "Бейкером"
"пр" = "Бейкеру"

[[male]]
"им" = "Чайлд"
"ро" = "Чайлда"
"да" = "Чайлду"
"ви" = "Чайлда"
"тв" = "Чайлдом"
"пр" = "Чайлде"

[[male]]
"им" = "Купер"
"ро" = "Купера"
"да" = "Куперу"
"ви" = "Купера"
"тв" = "Купером"
"пр" = "Купере"

[[female]]
"им" = "Бейкер"

[[female]]
"им" = "Чайлд"

[[female]]
"им" = "Купер"