[hugh]  # the player character
"им" = "Хью"

[mike]  # the brother
"им" = "Майк"
"ро" = "Майка"
"да" = "Майку"
"ви" = "Майка"
"тв" = "Майком"
"пр" = "Майке"

[lilia]  # the mother
"им" = "Лилия"
"ро" = "Лилии"
"да" = "Лилии"
"ви" = "Лилию"
"тв" = "Лилией"
"пр" = "Лилии"

[kinds_male]  # player family name
"им" = "Кайндс"
"ро" = "Кайндса"
"да" = "Кайндсу"
"ви" = "Кайндса"
"тв" = "Кайндсом"
"пр" = "Кайндсе"

[kinds_female]
"им" = "Кайндс"
