[[houses]]
start = [57, 31]
end = [71, 37]
entrance = [70, 33]

[[houses]]
start = [146, 7]
end = [166, 13]
entrance = [155, 14]

[[houses]]
start = [161, 29]
end = [168, 34]
entrance = [163, 29]

[[houses]]
start = [149, 29]
end = [162, 34]
entrance = [157, 29]

[[houses]]
start = [98, 44]
end = [176, 53]
entrance = [101, 44]

[[houses]]
start = [147, 44]
end = [168, 62]
entrance = [150, 44]

[[houses]]  # player's house
start = [184, 48]
end = [211, 61]
entrance = [189, 48]
reserved_for = "kinds"



[[zones]]
name."им" = "рыбацкая хижина"  # TODO complex Name.auto
center = [83, 11]
attractiveness = 10

[[zones]]
name = "таверна"
center = [121, 24]
attractiveness = 30
is_social = true

[[zones]]
name."им" = "разрушенный дом"
name."ро" = "разрушенного дома"
name."да" = "разрушенному дому"
name."ви" = "разрушенный дом"
name."тв" = "разрушенным домом"
name."пр" = "разрушенном доме"
center = [18, 46]
attractiveness = 5

[[zones]]
name = "пустырь за таверной"
center = [202, 10]
attractiveness = 5

[[zones]]
name = "лес"
center = [25, 16]
attractiveness = 5