female = []

[[male]]
"им" = "Ханн"
"ро" = "Ханна"
"да" = "Ханну"
"ви" = "Ханна"
"тв" = "Ханном"
"пр" = "Ханне"

[[male]]
"им" = "Хобб"
"ро" = "Хобба"
"да" = "Хоббу"
"ви" = "Хобба"
"тв" = "Хоббом"
"пр" = "Хоббе"