[kinds]  # player family name
male."им" = "Кайндс"
male."ро" = "Кайндса"
male."да" = "Кайндсу"
male."ви" = "Кайндса"
male."тв" = "Кайндсом"
male."пр" = "Кайндсе"
female."им" = "Кайндс"

[wild]  # girl from the village
female."им" = "Уайлд"