[kinds_male]  # player family name
"им" = "Кайндс"
"ро" = "Кайндса"
"да" = "Кайндсу"
"ви" = "Кайндса"
"тв" = "Кайндсом"
"пр" = "Кайндсе"

[kinds_female]  # TODO maybe get rid of postfixes?
"им" = "Кайндс"

[wild_female]  # girl from the village
"им" = "Уайлд"