female = []

[[male]]
"им" = "Ханн"
"ро" = "Ханна"
"да" = "Ханну"
"ви" = "Ханна"
"тв" = "Ханном"
"пр" = "Ханне"

[[male]]
"им" = "Хобб"
"ро" = "Хобба"
"да" = "Хоббу"
"ви" = "Хобба"
"тв" = "Хоббом"
"пр" = "Хоббе"

[[male]]
"им" = "Фирмин"
"ро" = "Фирмина"
"да" = "Фирмину"
"ви" = "Фирмина"
"тв" = "Фирмином"
"пр" = "Фирмине"

[[male]]
"им" = "Худд"
"ро" = "Худда"
"да" = "Худду"
"ви" = "Худда"
"тв" = "Худдом"
"пр" = "Худде"

[[male]]
"им" = "Од"
"ро" = "Ода"
"да" = "Оду"
"ви" = "Ода"
"тв" = "Одом"
"пр" = "Оде"

[[male]]
"им" = "Пат"
"ро" = "Пата"
"да" = "Пату"
"ви" = "Пата"
"тв" = "Патом"
"пр" = "Пате"