[[names]]
male."им" = "Бейкер"
male."ро" = "Бейкера"
male."да" = "Бейкеру"
male."ви" = "Бейкера"
male."тв" = "Бейкером"
male."пр" = "Бейкере"
female."им" = "Бейкер"

[[names]]
male."им" = "Вуд"
male."ро" = "Вуда"
male."да" = "Вуду"
male."ви" = "Вуда"
male."тв" = "Вудом"
male."пр" = "Вуде"
female."им" = "Вуд"