name: Search for TODO!s
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install ripgrep
      run: |
        sudo apt-get install ripgrep
    - name: Search for "TODO!"
      run: |
        sh scripts/todonow.zsh
