name: Run tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install ripgrep
      run: |
        sudo apt-get install ripgrep
    - name: Search for "TODO!"
      run: |
        rg 'TODO!' . && exit 1 || exit 0
